"""BioProver SMT encoding layer.

Provides expression IR, algebraic simplification, ODE discretization,
Hill function encoding, parameter uncertainty encoding, SMT-LIB
serialization, and incremental encoding management.
"""

from .expression import (
    Abs,
    Add,
    And,
    Const,
    Cos,
    Div,
    Eq,
    Exists,
    Exp,
    ExprNode,
    ForAll,
    Ge,
    Gt,
    HillAct,
    HillRep,
    Implies,
    Interval,
    Ite,
    Le,
    Log,
    Lt,
    Max,
    Min,
    Mul,
    Neg,
    Not,
    ONE,
    Or,
    Pow,
    Sin,
    Sqrt,
    TWO,
    Var,
    ZERO,
    collect_nodes,
    const,
    const_value,
    is_const,
    is_var,
    map_expr,
    prod_exprs,
    sum_exprs,
    var,
)
from .hill_encoding import (
    ApproxError,
    FragmentKind,
    HillEncodingConfig,
    classify_fragment,
    encode_dimerization,
    encode_hill_act_integer,
    encode_hill_act_pwl,
    encode_hill_act_taylor,
    encode_hill_monotone_bounds,
    encode_hill_node,
    encode_hill_rep_integer,
    encode_hill_rep_pwl,
    encode_mass_action,
    encode_michaelis_menten,
)
from .incremental import IncrementalEncoder, IncrementalStats
from .ode_encoding import (
    ConservationLaw,
    DiscretizationMethod,
    EncodingSizeEstimate,
    ODEEncoding,
    ODESystem,
    Parameter,
    Species,
    encode_ode,
    encode_ode_auto,
    encode_ode_incremental,
    estimate_encoding_size,
    select_time_step,
    state_var,
)
from .parameter_encoding import (
    DiscretizationResult,
    ParameterConstraints,
    ParameterRole,
    QuantifiedParam,
    discretize_parameter_space,
    encode_corners,
    encode_existential,
    encode_interval_subdivision,
    encode_robust_synthesis,
    encode_universal,
    generate_parameter_constraints,
    parameter_bound_constraints,
    skolemize,
)
from .simplifier import (
    SimplifyConfig,
    SimplifyStats,
    interval_eval,
    normalize_polynomial,
    simplify,
    simplify_fully,
    IVal,
)
from .smtlib_serializer import (
    SMTLogic,
    SMTResult,
    SerializerConfig,
    auto_select_logic,
    emit_assert,
    emit_check_sat,
    emit_check_sat_assuming,
    emit_get_model,
    emit_get_value,
    emit_maximize,
    emit_minimize,
    emit_pop,
    emit_push,
    expr_to_smtlib,
    parse_smt_response,
    serialize_smtlib,
    write_smtlib_file,
)

__all__ = [
    # expression
    "ExprNode", "Const", "Var", "Add", "Mul", "Div", "Neg", "Pow",
    "Exp", "Log", "Sin", "Cos", "Sqrt", "Abs", "Min", "Max",
    "HillAct", "HillRep", "ForAll", "Exists",
    "Lt", "Le", "Eq", "Ge", "Gt",
    "And", "Or", "Not", "Implies", "Ite",
    "Interval", "ZERO", "ONE", "TWO",
    "const", "var", "sum_exprs", "prod_exprs",
    "map_expr", "collect_nodes", "is_const", "is_var", "const_value",
    # simplifier
    "simplify", "simplify_fully", "SimplifyConfig", "SimplifyStats",
    "normalize_polynomial", "interval_eval", "IVal",
    # ode_encoding
    "Species", "Parameter", "ConservationLaw", "ODESystem",
    "DiscretizationMethod", "ODEEncoding", "EncodingSizeEstimate",
    "encode_ode", "encode_ode_auto", "encode_ode_incremental",
    "estimate_encoding_size", "select_time_step", "state_var",
    # hill_encoding
    "FragmentKind", "ApproxError", "HillEncodingConfig",
    "classify_fragment",
    "encode_hill_act_integer", "encode_hill_rep_integer",
    "encode_hill_act_pwl", "encode_hill_rep_pwl",
    "encode_hill_act_taylor",
    "encode_michaelis_menten", "encode_mass_action", "encode_dimerization",
    "encode_hill_monotone_bounds", "encode_hill_node",
    # parameter_encoding
    "ParameterRole", "QuantifiedParam",
    "encode_universal", "encode_existential", "encode_robust_synthesis",
    "discretize_parameter_space", "DiscretizationResult",
    "encode_corners", "encode_interval_subdivision",
    "skolemize", "parameter_bound_constraints",
    "generate_parameter_constraints", "ParameterConstraints",
    # smtlib_serializer
    "SMTLogic", "SerializerConfig", "SMTResult",
    "auto_select_logic", "expr_to_smtlib", "serialize_smtlib",
    "write_smtlib_file", "parse_smt_response",
    "emit_push", "emit_pop", "emit_assert", "emit_check_sat",
    "emit_check_sat_assuming", "emit_get_model", "emit_get_value",
    "emit_minimize", "emit_maximize",
    # incremental
    "IncrementalEncoder", "IncrementalStats",
]
