"""BioProver AI heuristic engine.

Provides GNN circuit encoding, predicate prediction, refinement heuristic
learning, and robustness surrogate models for CEGAR-driven synthetic
biology verification and repair.  All inference runs on CPU (pure NumPy).
"""

from bioprover.ai.feature_extraction import (
    AbstractionFeatures,
    CircuitFeatures,
    CounterexampleFeatures,
    FeatureNormalizer,
    MinMaxNormalizer,
    extract_abstraction_features,
    extract_circuit_features,
    extract_counterexample_features,
    feature_correlation_matrix,
    feature_importance_permutation,
    select_features_variance,
)
from bioprover.ai.gnn_encoder import (
    BatchedGraphs,
    CircuitEncoder,
    CircuitGraph,
    EdgeType,
    GraphReadout,
    GraphSAGEEncoder,
    GraphSAGELayer,
    GraphSAGELayerWeights,
    NeighborSampler,
    NodeFeatureNormalizer,
    batch_graphs,
    biomodel_to_graph,
    readout_attention,
    readout_max,
    readout_mean,
    unbatch_embeddings,
)
from bioprover.ai.predicate_predictor import (
    CandidatePredicate,
    Dropout,
    MLP,
    MLPLayerWeights,
    PredictionQualityMonitor,
    PredicatePredictor,
    QuantizedMLP,
    QuantizedPredicatePredictor,
    generate_candidate_predicates,
)
from bioprover.ai.refinement_learner import (
    Adam,
    CEGARState,
    CurriculumScheduler,
    DifferentiableMLP,
    ImitationLearner,
    RefinementExample,
    ReplayBuffer,
    augment_species_permutation,
)
from bioprover.ai.robustness_surrogate import (
    GaussianProcessRegressor,
    MaternKernel,
    RBFKernel,
    RobustnessSurrogate,
    expected_improvement,
    optimize_acquisition,
    thompson_sampling,
    upper_confidence_bound,
)
from bioprover.ai.training_pipeline import (
    CircuitData,
    CosineAnnealingLR,
    CrossValidator,
    DataAugmenter,
    Dataset,
    EarlyStopping,
    MLEvaluator,
    StepLR,
    Trainer,
    TrainingConfig,
    TrainingDataGenerator,
    TrainingReport,
    VerificationStep,
    VerificationTrace,
    accuracy,
    load_checkpoint,
    mrr,
    ndcg,
    save_checkpoint,
    speedup_ratio,
)

__all__ = [
    # feature_extraction
    "AbstractionFeatures",
    "CircuitFeatures",
    "CounterexampleFeatures",
    "FeatureNormalizer",
    "MinMaxNormalizer",
    "extract_abstraction_features",
    "extract_circuit_features",
    "extract_counterexample_features",
    "feature_correlation_matrix",
    "feature_importance_permutation",
    "select_features_variance",
    # gnn_encoder
    "BatchedGraphs",
    "CircuitEncoder",
    "CircuitGraph",
    "EdgeType",
    "GraphReadout",
    "GraphSAGEEncoder",
    "GraphSAGELayer",
    "GraphSAGELayerWeights",
    "NeighborSampler",
    "NodeFeatureNormalizer",
    "batch_graphs",
    "biomodel_to_graph",
    "readout_attention",
    "readout_max",
    "readout_mean",
    "unbatch_embeddings",
    # predicate_predictor
    "CandidatePredicate",
    "Dropout",
    "MLP",
    "MLPLayerWeights",
    "PredictionQualityMonitor",
    "PredicatePredictor",
    "QuantizedMLP",
    "QuantizedPredicatePredictor",
    "generate_candidate_predicates",
    # refinement_learner
    "Adam",
    "CEGARState",
    "CurriculumScheduler",
    "DifferentiableMLP",
    "ImitationLearner",
    "RefinementExample",
    "ReplayBuffer",
    "augment_species_permutation",
    # robustness_surrogate
    "GaussianProcessRegressor",
    "MaternKernel",
    "RBFKernel",
    "RobustnessSurrogate",
    "expected_improvement",
    "optimize_acquisition",
    "thompson_sampling",
    "upper_confidence_bound",
    # training_pipeline
    "CircuitData",
    "CosineAnnealingLR",
    "CrossValidator",
    "DataAugmenter",
    "Dataset",
    "EarlyStopping",
    "MLEvaluator",
    "StepLR",
    "Trainer",
    "TrainingConfig",
    "TrainingDataGenerator",
    "TrainingReport",
    "VerificationStep",
    "VerificationTrace",
    "accuracy",
    "load_checkpoint",
    "mrr",
    "ndcg",
    "save_checkpoint",
    "speedup_ratio",
]
